/**
 * GALLERY SECTION - Responsive Bento + Waterfall
 * Desktop: structured bento grid (like Image 1)
 * Mobile: staggered waterfall columns (like Image 2)
 */

export function GallerySection() {
  const galleryImages = [
    {
      id: 1,
      url: "https://sqevbzmyxfydanimdcwp.supabase.co/storage/v1/object/public/post-images/1776610094048-np2ehp.png",
      title: "Hair Salon",
      category: "Beauty & Personal Care",
      objectPosition: "center",
    },
    {
      id: 2,
      url: "https://image.pollinations.ai/prompt/Professional%20photography%20of%20A%20medium%20scene%20captures%20a%20freshly%20sliced%20chicken%20shawarma%20wrap%20with%20vibrant%20vegetables%20and%20creamy%20tahini%20resting%20on%20a%20heavily%20textured%20warm%20wooden%20table%20next%20to%20a%20navy%20blue?width=1024&height=1024&nologo=true&seed=842551&model=flux",
      title: "Shawarma Wrap",
      category: "Food & Beverage",
      objectPosition: "center",
    },
    {
      id: 3,
      url: "https://image.pollinations.ai/prompt/Professional%20photography%20of%20A%20detail%20close%20up%20captures%20a%20vibrant%20arrangement%20of%20sliced%20bright%20orange%20roasted%20peppers%20and%20fresh%20lemon%20wedges%20resting%20on%20a%20warm%20textured%20wood%20prep%20surface%20In%20the%20soft%20foc?width=1024&height=1024&nologo=true&seed=604677&model=flux",
      title: "Fresh Ingredients",
      category: "Food & Beverage",
      objectPosition: "center",
    },
    {
      id: 4,
      url: "https://sqevbzmyxfydanimdcwp.supabase.co/storage/v1/object/public/post-images/1776435133504-evnkrh.png",
      title: "Yoga Studio",
      category: "Health & Wellness",
      objectPosition: "top",
    },
    {
      id: 5,
      url: "https://sqevbzmyxfydanimdcwp.supabase.co/storage/v1/object/public/post-images/1776289007259-cqe5u.png",
      title: "Insurance Broker",
      category: "Professional Services",
      objectPosition: "center",
    },
    {
      id: 6,
      url: "https://sqevbzmyxfydanimdcwp.supabase.co/storage/v1/object/public/post-images/1775921823175-y3nmxi.png",
      title: "Open Patio",
      category: "Restaurants",
      objectPosition: "center",
    },
  ];

  const Overlay = ({ title, category }: { title: string; category: string }) => (
    <>
      <div className="absolute inset-0 bg-black/0 group-hover:bg-black/40 transition-colors duration-300 rounded-xl" />
      <div className="absolute inset-0 flex flex-col justify-end p-3 bg-gradient-to-t from-black/70 via-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 rounded-xl">
        <p className="text-white font-semibold text-sm leading-tight">{title}</p>
        <p className="text-white/70 text-xs mt-0.5">{category}</p>
      </div>
    </>
  );

  return (
    <section className="bg-white py-12 md:py-16 border-b">
      <div className="mx-auto max-w-6xl px-4 sm:px-6">
        {/* Section Header */}
        <div className="mb-8">
          <h2 className="text-2xl md:text-3xl font-bold mb-3 text-slate-900">
            Real Posts. Real Results.
          </h2>
          <p className="text-slate-600 max-w-2xl text-sm md:text-base">
            Here's a collection of images generated by Shoreline Studio for Toronto businesses.
            Each one is tailored to their business, neighborhood, voice, and audience.
          </p>
        </div>

        {/* ─── DESKTOP BENTO GRID (hidden on mobile) ─── */}
        {/*
          Layout:
          [ Hair Salon (tall) ] [ Shawarma ] [ Ingredients ] [ Patio (tall) ]
          [ Hair Salon (tall) ] [    Yoga (wide 2-col)     ] [ Patio (tall) ]
                                              [ Insurance  ]
          
          Uses named grid-template-areas for precise placement.
        */}
        {/*
          Desktop layout (6 cards):
          [ Hair (tall 2 rows) ] [ Shawarma ] [ Ingredients ] [ Patio (tall 2 rows) ]
          [ Hair (tall 2 rows) ] [ Yoga (wide, spans 2 cols)  ] [ Patio (tall 2 rows) ]
          becomes 4 cols × 2 rows with insurance swapped in for one of the top slots.

          Final layout:
          [ Hair ] [ Shawarma ] [ Yoga (wide) ] [ Patio ]
          [ Hair ] [ Insurance ] [ Yoga (wide) ] [ Patio ]
          + Ingredients takes the insurance slot top-right
          
          Cleaner: 3 cols × 2 rows + sidebar:
          [ Hair(tall) ][ Shawarma  ][ Ingredients ][ Patio(tall) ]
          [ Hair(tall) ][ Yoga wide spans 2 cols   ][ Patio(tall) ]
          ^^ insurance missing — fix: replace ingredients with insurance, add ingredients row 2

          Simplest correct 6-card layout:
          Col:    1          2           3          4
          Row 1: hair     shawarma  ingredients   patio
          Row 2: hair     insurance    yoga        patio
          Row 3: (none)   (none)       yoga        (none)  <- yoga spans rows 2-3

          Use 3 rows instead:
          Row 1: hair    shawarma   ingredients   patio
          Row 2: hair    insurance  yoga          patio
          yoga spans col 3, rows 2-3 but we only have 2 rows...

          Best fit with 2 rows × 4 cols — yoga spans 2 cols bottom, insurance replaces one top slot:
          [ hair ] [ shawarma ] [ yoga·· ] [ patio ]
          [ hair ] [ insur    ] [ yoga·· ] [ patio ]
          ingredients moved to mobile only? No — keep all 6.

          Final decision: 3 rows × 3 cols grid:
          [ hair(tall) ][ shawarma    ][ patio(tall) ]
          [ hair(tall) ][ yoga(wide)  ][ patio(tall) ]  <- yoga spans cols 2-3 row 2, but patio is col 3...

          Go with 4 cols, 2 rows, yoga wide center-bottom, insurance replaces ingredients top:
          Row1: hair | shawarma | insurance | patio
          Row2: hair | yoga·yoga·yoga(3cols?) | patio  <- yoga spans cols 2-3-4? but patio is col 4

          FINAL WORKING LAYOUT — 4 cols × 2 rows:
          Row1: hair | shawarma | ingredients | patio
          Row2: hair | yoga     | insurance   | patio
        */}
        <div
          className="hidden sm:grid gap-3 mb-8"
          style={{
            gridTemplateColumns: "1fr 1fr 1fr 1fr",
            gridTemplateRows: "220px 220px",
            gridTemplateAreas: `
              "hair  shawarma     ingredients  patio"
              "hair  yoga         insurance    patio"
            `,
          }}
        >
          {/* Hair Salon — tall left */}
          <div
            className="relative group overflow-hidden rounded-xl cursor-pointer shadow-sm hover:shadow-md transition-shadow duration-300"
            style={{ gridArea: "hair" }}
          >
            <img
              src={galleryImages[0].url}
              alt={galleryImages[0].title}
              className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
              style={{ objectPosition: galleryImages[0].objectPosition }}
            />
            <Overlay title={galleryImages[0].title} category={galleryImages[0].category} />
          </div>

          {/* Shawarma — top row col 2 */}
          <div
            className="relative group overflow-hidden rounded-xl cursor-pointer shadow-sm hover:shadow-md transition-shadow duration-300"
            style={{ gridArea: "shawarma" }}
          >
            <img
              src={galleryImages[1].url}
              alt={galleryImages[1].title}
              className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
              style={{ objectPosition: galleryImages[1].objectPosition }}
            />
            <Overlay title={galleryImages[1].title} category={galleryImages[1].category} />
          </div>

          {/* Ingredients — top row col 3 */}
          <div
            className="relative group overflow-hidden rounded-xl cursor-pointer shadow-sm hover:shadow-md transition-shadow duration-300"
            style={{ gridArea: "ingredients" }}
          >
            <img
              src={galleryImages[2].url}
              alt={galleryImages[2].title}
              className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
              style={{ objectPosition: galleryImages[2].objectPosition }}
            />
            <Overlay title={galleryImages[2].title} category={galleryImages[2].category} />
          </div>

          {/* Patio — tall right */}
          <div
            className="relative group overflow-hidden rounded-xl cursor-pointer shadow-sm hover:shadow-md transition-shadow duration-300"
            style={{ gridArea: "patio" }}
          >
            <img
              src={galleryImages[5].url}
              alt={galleryImages[5].title}
              className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
              style={{ objectPosition: galleryImages[5].objectPosition }}
            />
            <Overlay title={galleryImages[5].title} category={galleryImages[5].category} />
          </div>

          {/* Yoga — bottom row col 2, scaled to show full figure */}
          <div
            className="relative group overflow-hidden rounded-xl cursor-pointer shadow-sm hover:shadow-md transition-shadow duration-300"
            style={{ gridArea: "yoga" }}
          >
            <img
              src={galleryImages[3].url}
              alt={galleryImages[3].title}
              className="w-full h-full object-cover transition-transform duration-500"
              style={{ objectPosition: galleryImages[3].objectPosition }}
            />
            <Overlay title={galleryImages[3].title} category={galleryImages[3].category} />
          </div>

          {/* Insurance — bottom row col 3 */}
          <div
            className="relative group overflow-hidden rounded-xl cursor-pointer shadow-sm hover:shadow-md transition-shadow duration-300"
            style={{ gridArea: "insurance" }}
          >
            <img
              src={galleryImages[4].url}
              alt={galleryImages[4].title}
              className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
              style={{ objectPosition: galleryImages[4].objectPosition }}
            />
            <Overlay title={galleryImages[4].title} category={galleryImages[4].category} />
          </div>
        </div>

        {/* ─── MOBILE STAGGERED WATERFALL (visible on mobile only) ─── */}
        {/*
          2 CSS columns. Heights are tuned so both columns sum to ~470px total:
          Col 1 (items 1,3,5): 160 + 145 + 155 = 460px
          Col 2 (items 2,4,6): 130 + 175 + 155 = 460px
          Gap (10px) is added between cards, so columns stay balanced.
        */}
        <div
          className="sm:hidden mb-8"
          style={{
            columnCount: 2,
            columnGap: "10px",
          }}
        >
          {/*
            Col 1: Hair(tall) + Ingredients + Insurance  = 220 + 140 + 140 = 500px
            Col 2: Yoga + Shawarma + Patio(tall)         = 140 + 140 + 220 = 500px
            Tall cards anchor outside columns, small cards fill middle — no gap.
          */}
          {[
            { img: galleryImages[0], height: "250px", objPos: "center" },  // Col1: Hair — tall
            { img: galleryImages[3], height: "160px", objPos: "center 20%" },  // Col2: Yoga — no scale
            { img: galleryImages[2], height: "160px", objPos: "center" },  // Col1: Ingredients
            { img: galleryImages[1], height: "160px", objPos: "center" },  // Col2: Shawarma
            { img: galleryImages[4], height: "160px", objPos: "center" },  // Col1: Insurance
            { img: galleryImages[5], height: "250px", objPos: "center" },  // Col2: Patio — tall
          ].map(({ img, height, objPos }: any) => (
            <div
              key={img.id}
              className="relative group overflow-hidden rounded-xl cursor-pointer shadow-sm mb-[10px]"
              style={{ breakInside: "avoid", height }}
            >
              <img
                src={img.url}
                alt={img.title}
                className="w-full h-full object-cover"
                style={{ objectPosition: objPos }}
              />
              {/* Always-visible subtle gradient + label on mobile */}
              <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent rounded-xl" />
              <div className="absolute bottom-0 left-0 right-0 p-2">
                <p className="text-white font-semibold text-xs leading-tight">{img.title}</p>
                <p className="text-white/70 text-[10px]">{img.category}</p>
              </div>
            </div>
          ))}
        </div>

        {/* CTA */}
        <div className="text-center">
          <p className="text-slate-600 mb-2 text-sm md:text-base">
            Ready to see what Shoreline can generate for your business?
          </p>
          <p className="font-semibold text-cyan-800">Join the Waitlist</p>
        </div>
      </div>
    </section>
  );
}